accent = "#c4a7e7"
cursor = "#ebbcba"
foreground = "#e0def4"
background = "#191724"
selection_foreground = "#191724"
selection_background = "#ebbcba"

color0 = "#26233a"
color1 = "#eb6f92"
color2 = "#31748f"
color3 = "#f6c177"
color4 = "#9ccfd8"
color5 = "#c4a7e7"
color6 = "#9ccfd8"
color7 = "#e0def4"
color8 = "#6e6a86"
color9 = "#eb6f92"
color10 = "#31748f"
color11 = "#f6c177"
color12 = "#9ccfd8"
color13 = "#c4a7e7"
color14 = "#9ccfd8"
color15 = "#908caa"
